### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by janbrasna** [janbrasna/gha-dependabot-test#22]
- [x] 1. Groups, ecosystems
- [x] 2. Naming +scopes
- [x] 3. Docker & GHA tentatively
- [x] Update some majors
- [x] Check group naming & directories
- [ ] Name npm scopes manually (prod, dev, test?)
- [ ] ~Try excluding directory definitions~
- [ ] ~Adding explicit strategy~
- [ ] ~Verify pip recursive requirements improvement~
   (see ADR 006 why this is still subpar)
